sudo: required

language: php
php:
  - 7.1.9

services:
  - docker

branches:
  only:
    - master

before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get update
#  - sudo apt-get -y install docker-ce
#  - docker --version
#  - sudo rm /usr/local/bin/docker-compose
#  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#  - sudo chmod +x /usr/local/bin/docker-compose
#  - docker-compose --version

before_script:
  - cp .env-dist .env
  - source .env
  - docker-compose up -d --build
  - docker ps -a
  - while [ "$(curl -o /dev/null -Isw '%{http_code}\n' http://localhost/api/ping)" -ne "200" ]; do sleep 3; echo "Waiting API to be available..."; done
  - cd api
  - composer install
  - cd ..
  - cd backend
  - npm install
  - cd ..
  - cd frontend
  - npm install
  - cd ..

script:
  - cd api
  - composer run sniff
  - composer run test:unit
  - composer run test:functional
  - cd ..
  - cd frontend
  - npm run lint
  - npm run test
  - cd ..
  - cd backend
  - npm run lint
  - npm run test
  - cd ..

after_script:
  - docker-compose down

notifications:
  email: false
